### ISSUE TITLE
How to upload from browser?

### ISSUE THREAD

**Issue by sarink** [Azure/Azurite#255]
How in the world do you perform an upload from a web browser?

1. First of all, there will be CORS issues, despite setting all the right properties. You could workaround this by using a reverse proxy, I suppose (https://github.com/Azure/Azurite/issues/254)

2. Next, there will be auth issues. We have to use SAS, but how do you generate a SAS token? (by the way, the fact that we must use SAS in a browser environment is not immediately apparent to someone reading the docs, this took awhile to understand)

3. Ok, so maybe you built a reverse proxy and you figured out how to generate a SAS token. Where would you put it? The v10 SDK doesn't support connection strings. Fine, you can parse it out yourself. But then, even after all of this, if you try to stick the token on the `serviceURL`, the `sig` parameter will get mysteriously stripped away by the SDK. Cannot figure out how to make it stick.

Very puzzled/frustrated that there is no clear and easy way to upload a file from a browser to a cloud storage host. Isn't this the 90% use case?

```
2019-08-28T19:35:03.322Z 99be203a-b224-46b6-a454-542cb50b5dc5 info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://localhost/devstoreaccount1/aphstorage/937e7540-3678-4b64-ac54-405abe112ed4 RequestHeaders:{"accept-language":"en-US,en;q=0.9","accept-encoding":"gzip, deflate, br","referer":"http://localhost:3000/storage-poc","sec-fetch-site":"same-origin","origin":"http://localhost:3000","accept":"*/*","x-ms-client-request-id":"80877aeb-05d1-48ea-a595-13310f6c7a0a","x-ms-version":"2018-11-09","content-type":"application/octet-stream","sec-fetch-mode":"cors","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36","dnt":"1","x-ms-blob-type":"BlockBlob","cache-control":"no-cache","pragma":"no-cache","content-length":"368797","connection":"close","host":"localhost:3000"} ClientIP=172.28.0.1 Protocol=http HTTPVersion=1.1
2019-08-28T19:35:03.323Z 99be203a-b224-46b6-a454-542cb50b5dc5 info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=aphstorage Blob=937e7540-3678-4b64-ac54-405abe112ed4
2019-08-28T19:35:03.323Z 99be203a-b224-46b6-a454-542cb50b5dc5 verbose: DispatchMiddleware: Dispatching request...
2019-08-28T19:35:03.326Z 99be203a-b224-46b6-a454-542cb50b5dc5 info: DispatchMiddleware: Operation=BlockBlob_Upload
2019-08-28T19:35:03.326Z 99be203a-b224-46b6-a454-542cb50b5dc5 verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.
2019-08-28T19:35:03.326Z 99be203a-b224-46b6-a454-542cb50b5dc5 info: PublicAccessAuthenticator:validate() Start validation against public access.
2019-08-28T19:35:03.326Z 99be203a-b224-46b6-a454-542cb50b5dc5 debug: PublicAccessAuthenticator:validate() Getting account properties...
2019-08-28T19:35:03.326Z 99be203a-b224-46b6-a454-542cb50b5dc5 debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: aphstorage, blob: 937e7540-3678-4b64-ac54-405abe112ed4
2019-08-28T19:35:03.328Z 99be203a-b224-46b6-a454-542cb50b5dc5 debug: PublicAccessAuthenticator:validate() Skip public access authentication. Cannot get public access type for container aphstorage
2019-08-28T19:35:03.328Z 99be203a-b224-46b6-a454-542cb50b5dc5 info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.
2019-08-28T19:35:03.328Z 99be203a-b224-46b6-a454-542cb50b5dc5 info: BlobSharedKeyAuthenticator:validate() Request doesn't include valid authentication header. Skip shared key authentication.
2019-08-28T19:35:03.329Z 99be203a-b224-46b6-a454-542cb50b5dc5 info: AccountSASAuthenticator:validate() Start validation against account Shared Access Signature pattern.
2019-08-28T19:35:03.329Z 99be203a-b224-46b6-a454-542cb50b5dc5 debug: AccountSASAuthenticator:validate() Getting account properties...
2019-08-28T19:35:03.329Z 99be203a-b224-46b6-a454-542cb50b5dc5 debug: AccountSASAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: aphstorage, blob: 937e7540-3678-4b64-ac54-405abe112ed4
2019-08-28T19:35:03.329Z 99be203a-b224-46b6-a454-542cb50b5dc5 debug: AccountSASAuthenticator:validate() Got account properties successfully.
2019-08-28T19:35:03.329Z 99be203a-b224-46b6-a454-542cb50b5dc5 debug: AccountSASAuthenticator:validate() Retrieved signature from URL parameter sig: undefined
2019-08-28T19:35:03.329Z 99be203a-b224-46b6-a454-542cb50b5dc5 info: AccountSASAuthenticator:validate() Failed to get valid account SAS values from request.
2019-08-28T19:35:03.330Z 99be203a-b224-46b6-a454-542cb50b5dc5 info: BlobSASAuthenticator:validate() Start validation against blob service Shared Access Signature pattern.
2019-08-28T19:35:03.330Z 99be203a-b224-46b6-a454-542cb50b5dc5 debug: BlobSASAuthenticator:validate() Getting account properties...
2019-08-28T19:35:03.330Z 99be203a-b224-46b6-a454-542cb50b5dc5 debug: BlobSASAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: aphstorage, blob: 937e7540-3678-4b64-ac54-405abe112ed4
2019-08-28T19:35:03.330Z 99be203a-b224-46b6-a454-542cb50b5dc5 debug: BlobSASAuthenticator:validate() Got account properties successfully.
2019-08-28T19:35:03.330Z 99be203a-b224-46b6-a454-542cb50b5dc5 debug: BlobSASAuthenticator:validate() Retrieved signature from URL parameter sig: undefined
2019-08-28T19:35:03.330Z 99be203a-b224-46b6-a454-542cb50b5dc5 debug: BlobSASAuthenticator:validate() No signature found in request. Skip blob service SAS validation.
2019-08-28T19:35:03.335Z 99be203a-b224-46b6-a454-542cb50b5dc5 error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response
2019-08-28T19:35:03.336Z 99be203a-b224-46b6-a454-542cb50b5dc5 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.  ErrorHTTPStatusCode=403 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={"x-ms-error-code":"AuthorizationFailure","x-ms-request-id":"99be203a-b224-46b6-a454-542cb50b5dc5"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>AuthorizationFailure</Code>\n  <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\nRequestId:99be203a-b224-46b6-a454-542cb50b5dc5\nTime:2019-08-28T19:35:03.330Z</Message>\n</Error>" ErrorStack="StorageError: Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\n    at Function.getAuthorizationFailure (/opt/azurite/dist/src/blob/errors/StorageErrorFactory.js:83:16)\n    at authenticate.then.pass (/opt/azurite/dist/src/blob/authentication/AuthenticationMiddlewareFactory.js:22:56)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
2019-08-28T19:35:03.336Z 99be203a-b224-46b6-a454-542cb50b5dc5 error: ErrorMiddleware: Set HTTP code: 403
2019-08-28T19:35:03.336Z 99be203a-b224-46b6-a454-542cb50b5dc5 error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=AuthorizationFailure
2019-08-28T19:35:03.336Z 99be203a-b224-46b6-a454-542cb50b5dc5 error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=99be203a-b224-46b6-a454-542cb50b5dc5
2019-08-28T19:35:03.336Z 99be203a-b224-46b6-a454-542cb50b5dc5 error: ErrorMiddleware: Set content type: application/xml
2019-08-28T19:35:03.336Z 99be203a-b224-46b6-a454-542cb50b5dc5 error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>AuthorizationFailure</Code>\n  <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\nRequestId:99be203a-b224-46b6-a454-542cb50b5dc5\nTime:2019-08-28T19:35:03.330Z</Message>\n</Error>"
2019-08-28T19:35:03.338Z 99be203a-b224-46b6-a454-542cb50b5dc5 info: EndMiddleware: End response. TotalTimeInMS=17 StatusCode=403 StatusMessage=Forbidden Headers={"server":"Azurite-Blob/3.1.2-preview","x-ms-error-code":"AuthorizationFailure","x-ms-request-id":"99be203a-b224-46b6-a454-542cb50b5dc5","content-type":"application/xml"}
```

**Comment by XiaoningLiu** [comment]
@sarink As discussed in https://github.com/Azure/Azurite/issues/254, V3 doesn't support preflight requeests right now. So browsers will block most of the requests to Azurite.

For authentication. The pasted debug log show that you didn't use any key or SAS, so it expected the authentication is failed.

For SAS, you can get a SAS from Azure Portal, Storage Explorer, or generate the SAS by JS SDK in Node.js environment. It's another topic about how to use SAS with JS SDK though.

**Comment by sarink** [comment]
Hi @XiaoningLiu and thanks for your reply.

I have bypassed CORS issues by using a proxy. I think all that is left to do is generate a valid SAS for my azurite service? How does one go about doing that?

**Comment by XiaoningLiu** [comment]
@sarink 

SAS can be generated using account name & key. As Azurite's default account name & key are fixed. So this SAS can be reused for you:

`
?sv=2016-05-31&sig=LRGTHWfM1q8jiYTl6y%2FB9UfBOR6GxRaD6fEfVfyFcRU%3D&st=2018-08-29T07%3A20%3A57Z&se=2020-08-29T07%3A20%3A57Z&srt=sco&ss=bfqt&sp=racupwdl
`

Your can generate SAS by your self using JS SDK in Node.js runtime.

**Comment by sarink** [comment]
Thanks for generating it for me. Out of curiosity, are there any instructions on how to generate the SAS?

I'm still getting an authorization error :(. Here's the debug log:

```
2019-08-29T07:20:41.570Z 82aa0543-2585-4690-b44b-6e6c30b5fedc info: BlobStorageContextMiddleware: RequestMethod=PUT RequestURL=http://localhost/devstoreaccount1/aphstorage/c19d7a64-49d3-4672-ad4c-99a1fc3ca2be?sv=2017-04-17&ss=bfqt&srt=sco&sp=rwdlacup&se=2019-09-18T05:33:48Z&st=2017-09-16T21:33:48Z&spr=https,http&sig=S4WFjjmiuWEJTPqhaKeCqU90HQWHKrIqXMiDxXgfK1g%3D RequestHeaders:{"accept-language":"en-US,en;q=0.9","accept-encoding":"gzip, deflate, br","referer":"http://localhost:3000/storage-poc","sec-fetch-site":"same-origin","origin":"http://localhost:3000","accept":"*/*","x-ms-client-request-id":"882188e7-c558-4acc-89a4-0bd1705da542","x-ms-version":"2018-11-09","content-type":"application/octet-stream","sec-fetch-mode":"cors","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36","dnt":"1","x-ms-blob-type":"BlockBlob","cache-control":"no-cache","pragma":"no-cache","content-length":"125668","connection":"close","host":"localhost:3000"} ClientIP=172.28.0.1 Protocol=http HTTPVersion=1.1                              
2019-08-29T07:20:41.570Z 82aa0543-2585-4690-b44b-6e6c30b5fedc info: BlobStorageContextMiddleware: Account=devstoreaccount1 Container=aphstorage Blob=c19d7a64-49d3-4672-ad4c-99a1fc3ca2be                                                                                            
2019-08-29T07:20:41.570Z 82aa0543-2585-4690-b44b-6e6c30b5fedc verbose: DispatchMiddleware: Dispatching request...
2019-08-29T07:20:41.571Z 82aa0543-2585-4690-b44b-6e6c30b5fedc info: DispatchMiddleware: Operation=BlockBlob_Upload
2019-08-29T07:20:41.571Z 82aa0543-2585-4690-b44b-6e6c30b5fedc verbose: AuthenticationMiddlewareFactory:createAuthenticationMiddleware() Validating authentications.                                                                                                                  
2019-08-29T07:20:41.571Z 82aa0543-2585-4690-b44b-6e6c30b5fedc info: PublicAccessAuthenticator:validate() Start validation against public access.                                                                                                                                     
2019-08-29T07:20:41.571Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: PublicAccessAuthenticator:validate() Getting account properties...
2019-08-29T07:20:41.571Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: PublicAccessAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: aphstorage, blob: c19d7a64-49d3-4672-ad4c-99a1fc3ca2be                                                   
2019-08-29T07:20:41.571Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: PublicAccessAuthenticator:validate() Public access type for container aphstorage is "container"                                                                                                                 
2019-08-29T07:20:41.571Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: PublicAccessAuthenticator:validate() Operation BlockBlob_Upload is not in container neither blob level public access list. Validation failed.                                                                   
2019-08-29T07:20:41.571Z 82aa0543-2585-4690-b44b-6e6c30b5fedc info: BlobSharedKeyAuthenticator:validate() Start validation against account shared key authentication.                                                                                                                
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc info: BlobSharedKeyAuthenticator:validate() Request doesn't include valid authentication header. Skip shared key authentication.                                                                                       
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc info: AccountSASAuthenticator:validate() Start validation against account Shared Access Signature pattern.                                                                                                             
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: AccountSASAuthenticator:validate() Getting account properties...
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: AccountSASAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: aphstorage, blob: c19d7a64-49d3-4672-ad4c-99a1fc3ca2be                                                     
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: AccountSASAuthenticator:validate() Got account properties successfully.                                                                                                                                         
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: AccountSASAuthenticator:validate() Retrieved signature from URL parameter sig: S4WFjjmiuWEJTPqhaKeCqU90HQWHKrIqXMiDxXgfK1g=                                                                                     
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: AccountSASAuthenticator:validate() Successfully got valid account SAS values from request. {"version":"2017-04-17","protocol":"https,http","startTime":"2017-09-16T21:33:48Z","expiryTime":"2019-09-18T05:33:48Z","permissions":"rwdlacup","services":"bfqt","resourceTypes":"sco"}
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc info: AccountSASAuthenticator:validate() Validate signature based account key1.                                                                                                                                        
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: AccountSASAuthenticator:validate() String to sign is: "devstoreaccount1\nrwdlacup\nbfqt\nsco\n2017-09-16T21:33:48Z\n2019-09-18T05:33:48Z\n\nhttps,http\n2017-04-17\n"                                           
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: AccountSASAuthenticator:validate() Calculated signature is: j9OOS/Z+ODDsCU9Aq2pukXAfnYXUWgfhkYU32+Osv5o=                                                                                                        
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc info: AccountSASAuthenticator:validate() Signature based on key1 validation failed.                                                                                                                                    
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc info: BlobSASAuthenticator:validate() Start validation against blob service Shared Access Signature pattern.                                                                                                           
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: BlobSASAuthenticator:validate() Getting account properties...
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: BlobSASAuthenticator:validate() Retrieved account name from context: devstoreaccount1, container: aphstorage, blob: c19d7a64-49d3-4672-ad4c-99a1fc3ca2be                                                        
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: BlobSASAuthenticator:validate() Got account properties successfully.
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: BlobSASAuthenticator:validate() Retrieved signature from URL parameter sig: S4WFjjmiuWEJTPqhaKeCqU90HQWHKrIqXMiDxXgfK1g=                                                                                        
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc debug: BlobSASAuthenticator:validate() Signed resource type undefined is invalid. Skip blob service SAS validation.                                                                                                    
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc error: ErrorMiddleware: Received a MiddlewareError, fill error information to HTTP response                                                                                                                            
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.  ErrorHTTPStatusCode=403 ErrorHTTPStatusMessage=undefined ErrorHTTPHeaders={"x-ms-error-code":"AuthorizationFailure","x-ms-request-id":"82aa0543-2585-4690-b44b-6e6c30b5fedc"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>AuthorizationFailure</Code>\n  <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\nRequestId:82aa0543-2585-4690-b44b-6e6c30b5fedc\nTime:2019-08-29T07:20:41.572Z</Message>\n</Error>" ErrorStack="StorageError: Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\n    at Function.getAuthorizationFailure (/opt/azurite/dist/src/blob/errors/StorageErrorFactory.js:83:16)\n    at authenticate.then.pass (/opt/azurite/dist/src/blob/authentication/AuthenticationMiddlewareFactory.js:22:56)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"                                                                                                                                      
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc error: ErrorMiddleware: Set HTTP code: 403
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc error: ErrorMiddleware: Set HTTP Header: x-ms-error-code=AuthorizationFailure                                                                                                                                          
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc error: ErrorMiddleware: Set HTTP Header: x-ms-request-id=82aa0543-2585-4690-b44b-6e6c30b5fedc                                                                                                                          
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc error: ErrorMiddleware: Set content type: application/xml
2019-08-29T07:20:41.572Z 82aa0543-2585-4690-b44b-6e6c30b5fedc error: ErrorMiddleware: Set HTTP body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>AuthorizationFailure</Code>\n  <Message>Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature.\nRequestId:82aa0543-2585-4690-b44b-6e6c30b5fedc\nTime:2019-08-29T07:20:41.572Z</Message>\n</Error>"                                                                                                  
2019-08-29T07:20:41.573Z 82aa0543-2585-4690-b44b-6e6c30b5fedc info: EndMiddleware: End response. TotalTimeInMS=2 StatusCode=403 StatusMessage=Forbidden Headers={"server":"Azurite-Blob/3.1.2-preview","x-ms-error-code":"AuthorizationFailure","x-ms-request-id":"82aa0543-2585-4690-b44b-6e6c30b5fedc","content-type":"application/xml"}
```

**Comment by XiaoningLiu** [comment]
@sarink Please use the SAS in this issue, seems you are using wrong SAS instead of this..

?sv=2016-05-31&sig=LRGTHWfM1q8jiYTl6y%2FB9UfBOR6GxRaD6fEfVfyFcRU%3D&st=2018-08-29T07%3A20%3A57Z&se=2020-08-29T07%3A20%3A57Z&srt=sco&ss=bfqt&sp=racupwdl

**Comment by sarink** [comment]
🤦‍♂ Haha, thanks!! It's working :)
